### ISSUE TITLE
关于分解

### ISSUE THREAD

**Issue by JAsonT1202** [plumprc/MTS-Mixers#14]
您好，可以将factorized MLP block作为embedding前的预处理模块使用吗，望解答

**Comment by plumprc** [comment]
> 您好，可以将factorized MLP block作为embedding前的预处理模块使用吗，望解答

可以的，但是不建议，因为embedding会首先把数据嵌入到更高维的空间里，在高维空间里数据更容易有相关性

**Comment by JAsonT1202** [comment]
谢谢您的解答，那您对在embedding层后encoder前，插入一个factorized MLP block用作降噪处理有什么看法吗

**Comment by plumprc** [comment]
> 谢谢您的解答，那您对在embedding层后encoder前，插入一个factorized MLP block用作降噪处理有什么看法吗

也许可行，有不有效取决于你的数据
