### ISSUE TITLE
关于通道mlp的问题

### ISSUE THREAD

**Issue by wantoknows** [plumprc/MTS-Mixers#5]
非常感谢您的复现工作，我想请教一下，为什么只有在ECL,Traffic，PeMS04中用到了通道MLP，这是否是个普遍的方法。还有就是我几乎没有看到数据集同时使用TemporalMixing和ChannelMixing是否可以同时使用，如果通道数较多的时间序列是否也可以使用这个backbone，非常感谢您的工作！

**Comment by plumprc** [comment]
> 非常感谢您的复现工作，我想请教一下，为什么只有在ECL,Traffic，PeMS04中用到了通道MLP，这是否是个普遍的方法。还有就是我几乎没有看到数据集同时使用TemporalMixing和ChannelMixing是否可以同时使用，如果通道数较多的时间序列是否也可以使用这个backbone，非常感谢您的工作！

我们在论文的 Section 1 中讨论了时间序列的低秩性。简单来说，对于一个时间序列实例（time series instance） $X\in\mathbb{R}^{n\times c}$，我们不确定它的长度 $n$ 和通道数 $c$ 哪个大哪个小，从张量的角度来看，当 $n>>c$ 或 $c>>n$ 时势必会存在严重的低秩现象，这是我们考虑引入时序分解和通道分解的一个初始动机。数据集 ECL (#channel=321)，Traffic (#channel=862) 和 PeMS04 (#channel=921) 的通道数都很大，在我们的实验设置下 (seq_len=96)，这些通道之间几乎不可能是线性无关的，因此在这里使用通道分解会带来很明显的提升。您也可以尝试使用普通的 channel mlp 来处理这部分，但通常会带来性能上的降低。

题外话，虽然我们使用了 channel mixing 这样的字眼，但是针对目前的长时预测 benchmark，做通道间交互往往会导致不好的预测结果，这一点在 PatchTST 等使用了 Channel Independent trick 的后续工作中也有体现，所以我们这里强调的还是通道层面的分解，和 MLP-Mixer 中的 channel mixing 还是有点不同的。

**Comment by wantoknows** [comment]
非常感谢您的回答，在最近的实验中我尝试使用MTS来做为1个block通过一个dwconv来预测单通道的时间序列预测并没有表现出很好的结果，但可以在多通道时间预测中可以达到类似于attention的结果。
