### ISSUE TITLE
想请教一下

### ISSUE THREAD

**Issue by SmallCatShark** [plumprc/MTS-Mixers#8]
时间频率freq是不是使用mixer模型时不用考虑设值情况，然后rev的作用是什么？

**Comment by plumprc** [comment]
> 时间频率freq是不是使用mixer模型时不用考虑设值情况，然后rev的作用是什么？

freq是基于日期对输入进行编码，类似于位置编码，是基于attention的方法比较依赖的，mixer的具体实现当然也可以用，只是我们的实验发现其他比如卷积、MLP这些结构加入额外的编码会影响预测性能。

rev 表示是否使用 RevIN，你可以参考我们在论文和 README 里面写的内容，也可以参考 https://openreview.net/forum?id=cGDAkQo1C0p 和 https://arxiv.org/abs/2305.10721 具体了解 RevIN 的作用

**Comment by SmallCatShark** [comment]
谢谢，就是说RevIN对性能的影响较大是吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "plumprc/MTS-Mixers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 下午4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [plumprc/MTS-Mixers] 想请教一下 (Issue #8)





  
时间频率freq是不是使用mixer模型时不用考虑设值情况，然后rev的作用是什么？
  
freq是基于日期对输入进行编码，类似于位置编码，是基于attention的方法比较依赖的，mixer的具体实现当然也可以用，只是我们的实验发现其他比如卷积、MLP这些结构加入额外的编码会影响预测性能。
 
rev 表示是否使用 RevIN，你可以参考我们在论文和 README 里面写的内容，也可以参考 https://openreview.net/forum?id=cGDAkQo1C0p 和 https://arxiv.org/abs/2305.10721 具体了解 RevIN 的作用

**Comment by plumprc** [comment]
> 谢谢，就是说RevIN对性能的影响较大是吗

对的

**Comment by SmallCatShark** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月14日(星期二) 下午5:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [plumprc/MTS-Mixers] 想请教一下 (Issue #8)





  
谢谢，就是说RevIN对性能的影响较大是吗
  
对的
