### ISSUE TITLE
有个问题想确认一下

### ISSUE THREAD

**Issue by SmallCatShark** [plumprc/MTS-Mixers#9]
1.enc_in，dec_in的输入是特征的数目吗，包不包括target，例如一个数据集包括target有5个特征，其中一个特征是date，然后代码将date处理成了特征编码，mixer实际上没有用到这个特征，即对于mixer来说总的特征数目是4。在特征维度因子混合FactorizedChannelMixing（）模块中需要用到enc_in,，此时enc_in的值是4吗，如果我要将date保留不进行处理，此时对于mixer而言，enc_in是不是应该是5？
2.对于用到encoder-decoder模块的模型来说，enc_in和dec_in的值是不是特征数目-1
谢谢作者大大！

**Comment by plumprc** [comment]
> 1.enc_in，dec_in的输入是特征的数目吗，包不包括target，例如一个数据集包括target有5个特征，其中一个特征是date，然后代码将date处理成了特征编码，mixer实际上没有用到这个特征，即对于mixer来说总的特征数目是4。在特征维度因子混合FactorizedChannelMixing（）模块中需要用到enc_in,，此时enc_in的值是4吗，如果我要将date保留不进行处理，此时对于mixer而言，enc_in是不是应该是5？ 2.对于用到encoder-decoder模块的模型来说，enc_in和dec_in的值是不是特征数目-1 谢谢作者大大！

enc_in和dec_in就是时间序列的变量个数，不包括date，date相关的特征编码是单独处理的，和位置编码类似，需要用的话直接加上就行。你可以仔细看看 `exp/exp_main.py` 的代码，x_mark 和 y_mark 指的就是这些额外的编码，具体实现都在 `layers/Embedding.py` 里

**Comment by SmallCatShark** [comment]
意思就是所有模型，enc_in和dec_in的值都是不包含date列的，如我上面举得例子，就是4（包含target），当然如果要用，也是可以加上去变成5，是这个意思吗，大大


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "plumprc/MTS-Mixers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 晚上9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [plumprc/MTS-Mixers] 有个问题想确认一下 (Issue #9)





  
1.enc_in，dec_in的输入是特征的数目吗，包不包括target，例如一个数据集包括target有5个特征，其中一个特征是date，然后代码将date处理成了特征编码，mixer实际上没有用到这个特征，即对于mixer来说总的特征数目是4。在特征维度因子混合FactorizedChannelMixing（）模块中需要用到enc_in,，此时enc_in的值是4吗，如果我要将date保留不进行处理，此时对于mixer而言，enc_in是不是应该是5？ 2.对于用到encoder-decoder模块的模型来说，enc_in和dec_in的值是不是特征数目-1 谢谢作者大大！
  
enc_in和dec_in就是时间序列的变量个数，不包括date，date相关的特征编码是单独处理的，和位置编码类似，需要用的话直接加上就行。你可以仔细看看 exp/exp_main.py 的代码，x_mark 和 y_mark 指的就是这些额外的编码，具体实现都在 layers/Embedding.py 里

**Comment by plumprc** [comment]
> 意思就是所有模型，enc_in和dec_in的值都是不包含date列的，如我上面举得例子，就是4（包含target），当然如果要用，也是可以加上去变成5，是这个意思吗，大大

不用加，都是4，因为在读取数据的时候序列本身和日期是单独加载的，这部分用不用取决于你的模型，我在 `exp/exp_main.py` 里保留了两种用法，你可以参考125行到133行，要用的话就把 x_mark 和 y_mark 考虑进去
